require("pkg-configs.nvim-treesitter")
require("pkg-configs.mini-pick")
require("pkg-configs.indent-blankline")
require("pkg-configs.which-key")
require("pkg-configs.oil")
require("pkg-configs.mason")
require("pkg-configs.mason-lspconfig")
require("pkg-configs.blink")
