cargo = [
    "metapac",
]
winget = [
    "Docker.DockerDesktop",
    "Git.Git",
    "GitHub.cli",
    "JesseDuffield.lazygit",
    "Microsoft.AppInstaller",
    "Microsoft.Edge",
    "Microsoft.PowerToys",
    "Microsoft.UI.Xaml.2.7",
    "Microsoft.UI.Xaml.2.8",
    "Microsoft.VCLibs.Desktop.14",
    "Microsoft.VCRedist.2015+.x64",
    "Microsoft.VCRedist.2015+.x86",
    "Microsoft.VisualStudio.2022.BuildTools",
    "Microsoft.VisualStudioCode",
    "Microsoft.WindowsTerminal",
    "Modrinth.ModrinthApp",
    "Mozilla.Firefox",
    "Neovide.Neovide",
    "Neovim.Neovim.Nightly",
    "Netsdk.S3Browser",
    "Nushell.Nushell",
    "Rustlang.Rustup",
    "TheDocumentFoundation.LibreOffice",
    "WetOtter44.StrawberryMusicPlayer.MSVC",
    "Xmake-io.Xmake",
    "twpayne.chezmoi",
    "Ventoy.Ventoy",
]

